# Generated by Django 2.1.5 on 2019-01-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('symbol', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
